# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da411c70a0c0991f589053bae94fe95fcfedbdd4619475500945072348e937f892cd89e1e052d16abc1a0132cc2429a77df7e5b6e5fb5ceb9305af159572e1d8

test:
  secret_key_base: b3871959a4592eb45e0e4bb1eafc74580beb7c3fcf925234211eac1449c587963164c3207b36afffd4764656f803dd0115ef34b11c7c14eab0895dd672ff7f1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
